Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" #LTS

  config.vm.define "tebandamS" do |vm|
    vm.vm.hostname = "tebandamS"
    vm.vm.network "private_network", ip: "192.168.56.110"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    vm.vm.provision "shell", path: "scripts/provisionServer.sh"
  end
end
